//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\wellington\projects\lectures\compiler-from-scratch\lectures\MyCompiler\Parser\MyParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MyParserParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IMyParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>programStmt</c>
	/// labeled alternative in <see cref="MyParserParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramStmt([NotNull] MyParserParser.ProgramStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtPrint</c>
	/// labeled alternative in <see cref="MyParserParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtPrint([NotNull] MyParserParser.StmtPrintContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtRead</c>
	/// labeled alternative in <see cref="MyParserParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtRead([NotNull] MyParserParser.StmtReadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtAttr</c>
	/// labeled alternative in <see cref="MyParserParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtAttr([NotNull] MyParserParser.StmtAttrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stmtCond</c>
	/// labeled alternative in <see cref="MyParserParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtCond([NotNull] MyParserParser.StmtCondContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="MyParserParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] MyParserParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifElseStmt</c>
	/// labeled alternative in <see cref="MyParserParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseStmt([NotNull] MyParserParser.IfElseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>condExpresion</c>
	/// labeled alternative in <see cref="MyParserParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondExpresion([NotNull] MyParserParser.CondExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>condRelOp</c>
	/// labeled alternative in <see cref="MyParserParser.condExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondRelOp([NotNull] MyParserParser.CondRelOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="MyParserParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] MyParserParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printStr</c>
	/// labeled alternative in <see cref="MyParserParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStr([NotNull] MyParserParser.PrintStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printExpr</c>
	/// labeled alternative in <see cref="MyParserParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintExpr([NotNull] MyParserParser.PrintExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>readVar</c>
	/// labeled alternative in <see cref="MyParserParser.read"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadVar([NotNull] MyParserParser.ReadVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>attrExpr</c>
	/// labeled alternative in <see cref="MyParserParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrExpr([NotNull] MyParserParser.AttrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="MyParserParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprPlus([NotNull] MyParserParser.ExprPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="MyParserParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprMinus([NotNull] MyParserParser.ExprMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr1Empty</c>
	/// labeled alternative in <see cref="MyParserParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr1Empty([NotNull] MyParserParser.Expr1EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr1Mult</c>
	/// labeled alternative in <see cref="MyParserParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr1Mult([NotNull] MyParserParser.Expr1MultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr1Div</c>
	/// labeled alternative in <see cref="MyParserParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr1Div([NotNull] MyParserParser.Expr1DivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Empty</c>
	/// labeled alternative in <see cref="MyParserParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Empty([NotNull] MyParserParser.Expr2EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Par</c>
	/// labeled alternative in <see cref="MyParserParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Par([NotNull] MyParserParser.Expr2ParContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Num</c>
	/// labeled alternative in <see cref="MyParserParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Num([NotNull] MyParserParser.Expr2NumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr2Var</c>
	/// labeled alternative in <see cref="MyParserParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr2Var([NotNull] MyParserParser.Expr2VarContext context);
}
} // namespace Grammar
