//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\wellington\projects\lectures\compiler-from-scratch\lectures\intro-antlr\SimpleGrammar.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class SimpleGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EQ=1, EOL=2, OPEN=3, CLOSE=4, MOD=5, DIV=6, MUL=7, SUB=8, ADD=9, NUM=10, 
		PRINT=11, VAR=12, COMMENTS=13, WS=14;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"EQ", "EOL", "OPEN", "CLOSE", "MOD", "DIV", "MUL", "SUB", "ADD", "NUM", 
		"PRINT", "VAR", "COMMENTS", "WS"
	};


	public SimpleGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SimpleGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "';'", "'('", "')'", "'%'", "'/'", "'*'", "'-'", "'+'", null, 
		"'print'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EQ", "EOL", "OPEN", "CLOSE", "MOD", "DIV", "MUL", "SUB", "ADD", 
		"NUM", "PRINT", "VAR", "COMMENTS", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SimpleGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SimpleGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x10', 'P', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x6', '\v', '\x33', '\n', '\v', '\r', '\v', '\xE', '\v', '\x34', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x6', '\r', '>', '\n', '\r', '\r', '\r', '\xE', '\r', 
		'?', '\x3', '\xE', '\x3', '\xE', '\x6', '\xE', '\x44', '\n', '\xE', '\r', 
		'\xE', '\xE', '\xE', '\x45', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x6', '\xF', 'K', '\n', '\xF', '\r', '\xF', '\xE', '\xF', 'L', '\x3', 
		'\xF', '\x3', '\xF', '\x2', '\x2', '\x10', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x3', '\x2', '\x6', '\x3', '\x2', '\x32', ';', 
		'\x4', '\x2', '\x43', '\\', '\x63', '|', '\x5', '\x2', '\f', '\f', '\xF', 
		'\xF', '\x80', '\x80', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', 'S', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x5', '!', '\x3', 
		'\x2', '\x2', '\x2', '\a', '#', '\x3', '\x2', '\x2', '\x2', '\t', '%', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\'', '\x3', '\x2', '\x2', '\x2', '\r', 
		')', '\x3', '\x2', '\x2', '\x2', '\xF', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '-', '\x3', '\x2', '\x2', '\x2', '\x13', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x32', '\x3', '\x2', '\x2', '\x2', '\x17', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '=', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x1D', 'J', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', ' ', '\a', '?', '\x2', '\x2', ' ', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '!', '\"', '\a', '=', '\x2', '\x2', '\"', '\x6', '\x3', 
		'\x2', '\x2', '\x2', '#', '$', '\a', '*', '\x2', '\x2', '$', '\b', '\x3', 
		'\x2', '\x2', '\x2', '%', '&', '\a', '+', '\x2', '\x2', '&', '\n', '\x3', 
		'\x2', '\x2', '\x2', '\'', '(', '\a', '\'', '\x2', '\x2', '(', '\f', '\x3', 
		'\x2', '\x2', '\x2', ')', '*', '\a', '\x31', '\x2', '\x2', '*', '\xE', 
		'\x3', '\x2', '\x2', '\x2', '+', ',', '\a', ',', '\x2', '\x2', ',', '\x10', 
		'\x3', '\x2', '\x2', '\x2', '-', '.', '\a', '/', '\x2', '\x2', '.', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '/', '\x30', '\a', '-', '\x2', '\x2', '\x30', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x31', '\x33', '\t', '\x2', '\x2', 
		'\x2', '\x32', '\x31', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x34', '\x32', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x35', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x36', '\x37', '\a', 'r', '\x2', '\x2', '\x37', '\x38', '\a', 
		't', '\x2', '\x2', '\x38', '\x39', '\a', 'k', '\x2', '\x2', '\x39', ':', 
		'\a', 'p', '\x2', '\x2', ':', ';', '\a', 'v', '\x2', '\x2', ';', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '<', '>', '\t', '\x3', '\x2', '\x2', '=', 
		'<', '\x3', '\x2', '\x2', '\x2', '>', '?', '\x3', '\x2', '\x2', '\x2', 
		'?', '=', '\x3', '\x2', '\x2', '\x2', '?', '@', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x41', '\x43', '\a', '%', '\x2', 
		'\x2', '\x42', '\x44', '\t', '\x4', '\x2', '\x2', '\x43', '\x42', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'G', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\b', '\xE', 
		'\x2', '\x2', 'H', '\x1C', '\x3', '\x2', '\x2', '\x2', 'I', 'K', '\t', 
		'\x5', '\x2', '\x2', 'J', 'I', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\x3', 
		'\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'N', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\b', 
		'\xF', '\x2', '\x2', 'O', '\x1E', '\x3', '\x2', '\x2', '\x2', '\a', '\x2', 
		'\x34', '?', '\x45', 'L', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Grammar
