//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\wellington\projects\lectures\compiler-from-scratch\lectures\intro-antlr\SimpleGrammar.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SimpleGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ISimpleGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] SimpleGrammarParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] SimpleGrammarParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] SimpleGrammarParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] SimpleGrammarParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] SimpleGrammarParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] SimpleGrammarParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFact([NotNull] SimpleGrammarParser.FactContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFact([NotNull] SimpleGrammarParser.FactContext context);
}
} // namespace Grammar
