//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\wellington\projects\lectures\compiler-from-scratch\lectures\intro-antlr\SimpleGrammar.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISimpleGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class SimpleGrammarBaseListener : ISimpleGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] SimpleGrammarParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] SimpleGrammarParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] SimpleGrammarParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] SimpleGrammarParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] SimpleGrammarParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] SimpleGrammarParser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] SimpleGrammarParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] SimpleGrammarParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput([NotNull] SimpleGrammarParser.OutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput([NotNull] SimpleGrammarParser.OutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.show"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShow([NotNull] SimpleGrammarParser.ShowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.show"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShow([NotNull] SimpleGrammarParser.ShowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.follow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFollow([NotNull] SimpleGrammarParser.FollowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.follow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFollow([NotNull] SimpleGrammarParser.FollowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo([NotNull] SimpleGrammarParser.TipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo([NotNull] SimpleGrammarParser.TipoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.equals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquals([NotNull] SimpleGrammarParser.EqualsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.equals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquals([NotNull] SimpleGrammarParser.EqualsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.cont"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont([NotNull] SimpleGrammarParser.ContContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.cont"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont([NotNull] SimpleGrammarParser.ContContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] SimpleGrammarParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] SimpleGrammarParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRest([NotNull] SimpleGrammarParser.RestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRest([NotNull] SimpleGrammarParser.RestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.fact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFact([NotNull] SimpleGrammarParser.FactContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.fact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFact([NotNull] SimpleGrammarParser.FactContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.more"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMore([NotNull] SimpleGrammarParser.MoreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.more"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMore([NotNull] SimpleGrammarParser.MoreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] SimpleGrammarParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] SimpleGrammarParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.uif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUif([NotNull] SimpleGrammarParser.UifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.uif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUif([NotNull] SimpleGrammarParser.UifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] SimpleGrammarParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] SimpleGrammarParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp([NotNull] SimpleGrammarParser.CompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp([NotNull] SimpleGrammarParser.CompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOther([NotNull] SimpleGrammarParser.OtherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOther([NotNull] SimpleGrammarParser.OtherContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.uelse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUelse([NotNull] SimpleGrammarParser.UelseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.uelse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUelse([NotNull] SimpleGrammarParser.UelseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.uwhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUwhile([NotNull] SimpleGrammarParser.UwhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.uwhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUwhile([NotNull] SimpleGrammarParser.UwhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.ufor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUfor([NotNull] SimpleGrammarParser.UforContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.ufor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUfor([NotNull] SimpleGrammarParser.UforContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecl([NotNull] SimpleGrammarParser.DeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecl([NotNull] SimpleGrammarParser.DeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.incr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncr([NotNull] SimpleGrammarParser.IncrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.incr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncr([NotNull] SimpleGrammarParser.IncrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] SimpleGrammarParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] SimpleGrammarParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.par"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPar([NotNull] SimpleGrammarParser.ParContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.par"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPar([NotNull] SimpleGrammarParser.ParContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.cfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCfunction([NotNull] SimpleGrammarParser.CfunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.cfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCfunction([NotNull] SimpleGrammarParser.CfunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.cpar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCpar([NotNull] SimpleGrammarParser.CparContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.cpar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCpar([NotNull] SimpleGrammarParser.CparContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput([NotNull] SimpleGrammarParser.InputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput([NotNull] SimpleGrammarParser.InputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] SimpleGrammarParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] SimpleGrammarParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.umath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUmath([NotNull] SimpleGrammarParser.UmathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.umath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUmath([NotNull] SimpleGrammarParser.UmathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.mathpar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathpar([NotNull] SimpleGrammarParser.MathparContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.mathpar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathpar([NotNull] SimpleGrammarParser.MathparContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.floor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloor([NotNull] SimpleGrammarParser.FloorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.floor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloor([NotNull] SimpleGrammarParser.FloorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.ceil"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCeil([NotNull] SimpleGrammarParser.CeilContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.ceil"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCeil([NotNull] SimpleGrammarParser.CeilContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.sqrt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqrt([NotNull] SimpleGrammarParser.SqrtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.sqrt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqrt([NotNull] SimpleGrammarParser.SqrtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.pot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPot([NotNull] SimpleGrammarParser.PotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.pot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPot([NotNull] SimpleGrammarParser.PotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.fmax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFmax([NotNull] SimpleGrammarParser.FmaxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.fmax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFmax([NotNull] SimpleGrammarParser.FmaxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.fmin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFmin([NotNull] SimpleGrammarParser.FminContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.fmin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFmin([NotNull] SimpleGrammarParser.FminContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleGrammarParser.rint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRint([NotNull] SimpleGrammarParser.RintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleGrammarParser.rint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRint([NotNull] SimpleGrammarParser.RintContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Grammar
