//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\wellington\projects\lectures\compiler-from-scratch\lectures\intro-antlr\SimpleGrammar.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SimpleGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ISimpleGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] SimpleGrammarParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] SimpleGrammarParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode([NotNull] SimpleGrammarParser.CodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] SimpleGrammarParser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput([NotNull] SimpleGrammarParser.OutputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.show"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShow([NotNull] SimpleGrammarParser.ShowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.follow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFollow([NotNull] SimpleGrammarParser.FollowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo([NotNull] SimpleGrammarParser.TipoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.equals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquals([NotNull] SimpleGrammarParser.EqualsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.cont"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont([NotNull] SimpleGrammarParser.ContContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] SimpleGrammarParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.rest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRest([NotNull] SimpleGrammarParser.RestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFact([NotNull] SimpleGrammarParser.FactContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.more"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMore([NotNull] SimpleGrammarParser.MoreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] SimpleGrammarParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.uif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUif([NotNull] SimpleGrammarParser.UifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] SimpleGrammarParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp([NotNull] SimpleGrammarParser.CompContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther([NotNull] SimpleGrammarParser.OtherContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.uelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUelse([NotNull] SimpleGrammarParser.UelseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.uwhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUwhile([NotNull] SimpleGrammarParser.UwhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.ufor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUfor([NotNull] SimpleGrammarParser.UforContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecl([NotNull] SimpleGrammarParser.DeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.incr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncr([NotNull] SimpleGrammarParser.IncrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] SimpleGrammarParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.par"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPar([NotNull] SimpleGrammarParser.ParContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.cfunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCfunction([NotNull] SimpleGrammarParser.CfunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.cpar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCpar([NotNull] SimpleGrammarParser.CparContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] SimpleGrammarParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] SimpleGrammarParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.umath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUmath([NotNull] SimpleGrammarParser.UmathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.mathpar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathpar([NotNull] SimpleGrammarParser.MathparContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.floor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloor([NotNull] SimpleGrammarParser.FloorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.ceil"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCeil([NotNull] SimpleGrammarParser.CeilContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.sqrt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqrt([NotNull] SimpleGrammarParser.SqrtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.pot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPot([NotNull] SimpleGrammarParser.PotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.fmax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFmax([NotNull] SimpleGrammarParser.FmaxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.fmin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFmin([NotNull] SimpleGrammarParser.FminContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleGrammarParser.rint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRint([NotNull] SimpleGrammarParser.RintContext context);
}
} // namespace Grammar
